### ISSUE TITLE
ScanContext repo missing

### ISSUE THREAD

**Issue by gc625-kodifly** [YWL0720/FAST-LOCALIZATION#2]
Hi, I noticed that https://github.com/irapkaist/scancontext returns a 404 error, would you happen to have your own fork of the repo you can link instead?

**Comment by YWL0720** [comment]
I'm sorry, the author of ScanContext updated his repository a few days ago. I will submit a new README later.

**Comment by YWL0720** [comment]
I have already updated the README.
