### ISSUE TITLE
Map load issue

### ISSUE THREAD

**Issue by giangdao1402** [YWL0720/FAST-LOCALIZATION#3]
Why when i load map successfully it's quite bad
![livox](https://github.com/YWL0720/FAST-LOCALIZATION/assets/98149078/4aa1145d-fbe2-4e9e-94c0-eb7b43b88522)
In this test i used Livox bag by HKU

**Comment by YWL0720** [comment]
I recommend checking whether the number of poses in pose.json is the same as the number of pcd files, or try deleting the existing pose.json and pcd files and rerun the code.

**Comment by giangdao1402** [comment]
Thank you so much !

**Comment by lzlz-lz** [comment]
@giangdao1402 
After I finish executing roslaunch fast_localization localization_mid360.launch, when I press Enter in the terminal, it displays that the map has been loaded successfully, but rviz is empty.

![Image](https://github.com/user-attachments/assets/f5d1c9ae-5bcb-483d-a547-3bd1d5c3d918)
How can this issue be resolved?
