### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by wwruiiii** [YWL0720/FAST-LOCALIZATION#4]
尊敬的作者您好,我在阅读代码的过程中，发现laserMapping.cpp文件中的“Nearest_Points“变量没有被赋值但是多处被用到，请问这是正确做法么？若您看到给我回复，我万分感谢。

**Comment by YWL0720** [comment]
laserMapping.cpp中的第687行，创建了一个引用points_near，其直接引用Nearest_Points[i]
```cpp
auto &points_near = Nearest_Points[i];
```
其值随后在第692行中被修改
```cpp
ikdtree.Nearest_Search(point_world, NUM_MATCH_POINTS, points_near, pointSearchSqDis);
```

**Comment by wwruiiii** [comment]
哇，好及时，谢谢！是我看的不仔细了
