### ISSUE TITLE
关于代码适配的环境

### ISSUE THREAD

**Issue by zengy5** [YWL0720/FAST-LOCALIZATION#6]
作者您好，很感谢您出色的工作，在室内的环境中您的代码可以很完美的运行，但是我在大型的室外数据集中测试发现代码并不能自动找到初始位姿，请问一下在哪里可以调整相关的参数呢，感激不尽

**Comment by zengy5** [comment]
我已经解决问题了，只要修改一下scantext.h中的参数PC_MAX_RADIUS就可以了，再次感谢您的工作

**Comment by maomao0220** [comment]
请问在室外环境您是怎样调整的PC_MAX_RADIUS值？ @zengy5

**Comment by zengy5** [comment]
> 请问在室外环境您是怎样调整的PC_MAX_RADIUS值？ @zengy5

作者代码里scancontext只是用于搜索初始位姿用的，之后scancontext就没用了，所以实际上你需要知道你机器人大致的初始位姿距离地图原点多远，对应地修改最大搜索半径就行，或者也可以简单地把地图中最远点的距离设置为最大搜索半径 @maomao0220

**Comment by maomao0220** [comment]
好的，谢谢您的回复。还有一个问题：您在跑室外环境的时候，有没有试过同一地方录两个不同的bag包（起始方向或者位置稍有不同），一个用于建图一个用于重定位？我在实验的时候总是重定位不成功，而且实车测试的时候只有在起点相同时才可以定位成功，一旦在任意其他位置就会重定位失败，找不到匹配位姿，期待您的回复

**Comment by zengy5** [comment]
> 好的，谢谢您的回复。还有一个问题：您在跑室外环境的时候，有没有试过同一地方录两个不同的bag包（起始方向或者位置稍有不同），一个用于建图一个用于重定位？我在实验的时候总是重定位不成功，而且实车测试的时候只有在起点相同时才可以定位成功，一旦在任意其他位置就会重定位失败，找不到匹配位姿，期待您的回复

我们具体做法确实是你说的这样，用bag1建图，用bag2定位，录制环境是同一个场地，起点是不同位置，每个定位bag都可以正常初始化成功。如果你的数据不能的话，考虑两点：
1、雷达是不是360°的，因为scancontext论文中是以360°雷达为例，对于小视野的雷达能否使用，我也不清楚，或许会失效
2、注意起始位置的扫描结果是否在地图内部
@maomao0220
