### ISSUE TITLE
运行时资源占用率高

### ISSUE THREAD

**Issue by maomao0220** [YWL0720/FAST-LOCALIZATION#8]
您好，在运行代码时，top指令显示该定位算法的CPU占用率达到了100多，请问有什么好的解决方法？

**Comment by YWL0720** [comment]
在构建残差和搜索最近邻的时候会使用openmp并行加速，会导致cpu占用率升高。如果对实时性没有特别高的要求，可以取消并行化

**Comment by maomao0220** [comment]
感谢您的回复，请问具体该如何取消？

**Comment by YWL0720** [comment]
直接注释掉这几行就可以
https://github.com/YWL0720/FAST-LOCALIZATION/blob/93da4f462b8da16679c18a8aea9545ed4cb3c71b/src/laserMapping.cpp#L668C5-L671C11

**Comment by maomao0220** [comment]
好的，非常感谢，我去试试

**Comment by maomao0220** [comment]
在此之前试过降采样、改成在当前帧的局部地图进行重定位，发现资源占用率下降的很少（80-90）,请问如果想保持重定位实时的情况下，可以采取哪些措施？

**Comment by maomao0220** [comment]
试了您说的取消注释，资源占用率仍然很高，请问该如何优化？
![111](https://github.com/YWL0720/FAST-LOCALIZATION/assets/64572122/d431115a-67ea-4480-bd46-f
![222](https://github.com/YWL0720/FAST-LOCALIZATION/assets/64572122/3aaf2ea2-3a6a-499a-9895-cd49a2d88eb5)
a1c5c3ac2dc)

**Comment by maomao0220** [comment]
![111](https://github.com/YWL0720/FAST-LOCALIZATION/assets/64572122/a110f751-d017-4839-b477-be82250258c3)

**Comment by YWL0720** [comment]
也可以修改函数global_localization，当初始全局定位成功后，将其返回，减小部分计算开销。

**Comment by maomao0220** [comment]
是的，
1、在global_localization中初始化成功后，我是直接return，确实可以减少小部分资源占用，但是加上滤波处理后资源占用率依旧达到80- 90（目标是50-60），请问还有什么优化的方向吗？
![11111111](https://github.com/YWL0720/FAST-LOCALIZATION/assets/64572122/60503682-c203-4e57-afb0-389c21479c15)

2、我采用您说的注释加速代码，资源占用率并没有下降多少，请问有其他方法吗？

**Comment by YWL0720** [comment]
我这边测试去掉并行加速的话占用率还是下降的挺明显的，i7-10750H,跑ntu数据集16线的ouster，point filter num 3，体素下采样0.5，CPU占用率都在40%以下

**Comment by maomao0220** [comment]
十分感谢您的回复，我在建图和重定位的时候用的是速腾32线雷达，
1、请问建图和重定位的point filter num和 体素下采样参数是否要保持一致？
2、还有能否提供一下您使用的数据集的下载地址？

**Comment by YWL0720** [comment]
1.这个没有严格的要求，不同的话影响不会很大。
2.https://github.com/ntu-aris/ntu_viral_dataset
