### ISSUE TITLE
重定位失败

### ISSUE THREAD

**Issue by ZOUJIASHUAI** [YWL0720/FAST-LOCALIZATION#9]
[Init found] Nearest distance: 0.00467 btn 75 and 13.
[Init found] yaw diff: 0 deg.
[Init found] Nearest distance: 0.00467 btn 75 and 13.
[Init found] yaw diff: 0 deg.
[ INFO] [1709178568.229404289]: Global match map id = 13
[pcl::PCDReader::readHeader] Could not find file '/home/jason/3d_ws/src/FAST-LOCALIZATION/map/pcd/13.pcd'.
[pcl::IterativeClosestPoint::setInputTarget] Invalid or empty point cloud dataset given!
[pcl::registration::IterativeClosestPoint::compute] No input target dataset was given!
[pcl::IterativeClosestPoint::setInputTarget] Invalid or empty point cloud dataset given!
[pcl::registration::IterativeClosestPoint::compute] No input target dataset was given!
1 0 0 0
0 1 0 0
0 0 1 0
0 0 0 1
[ INFO] [1709178568.229518162]: Global localization successfully
![Uploading 2024-02-29 11-52-03 的屏幕截图.png…]()

**Comment by ZOUJIASHUAI** [comment]
@YWL0720 请问这个问题需要如何调整

**Comment by ZOUJIASHUAI** [comment]
![2024-02-29 11-52-03 的屏幕截图](https://github.com/YWL0720/FAST-LOCALIZATION/assets/19969444/3cf439f7-8579-4951-abcf-20fee0356bac)

**Comment by ZOUJIASHUAI** [comment]
看起来是没上线成功但是终端显示上线成功了

**Comment by YWL0720** [comment]
> [pcl::PCDReader::readHeader] Could not find file '/home/jason/3d_ws/src/FAST-LOCALIZATION/map/pcd/13.pcd'.

您好，这里显示无法加载初始定位匹配帧的pcd文件，需要保证map文件夹下的pcd文件序号是从0开始的

**Comment by YWL0720** [comment]
最近测试发现scan context会返回异常的匹配帧id 应该是导致上述问题的原因 最近会提交新的代码

**Comment by pedestrain123** [comment]
> 最近测试发现scan context会返回异常的匹配帧id 应该是导致上述问题的原因 最近会提交新的代码
请问重定位精度可以达到多少？
